export interface MBookMasterViewModel1 {
  id: string;
  workTemplateMilestoneId: string;
  paymentStatusId: string;
  length: number;
  width: number;
  heigth: number;
  actionableRoleId: string;
  date: string;
  workNotes: string;
  divisionId: string;
  statusName: string;
  paymentStatusName: string;
  isActive: boolean;
  isActionable: boolean;
  isEditable: boolean;
  isSubmitted: boolean;
  milestoneName: string;
  workTemplateId: string;
  tenderNumber: string;
  districtName: string;
  divisionName: string;
  gONumber: string;
  gODepartment: string;
  gOName: string;
  percentageCompleted: number;
  workType: string;
  files: FileMasterModel[] | null;
  approvalHistory: MBookApprovalHistoryViewModel[] | null;
  durationInDays: number;
  paymentPercentage: number;
  startDate: string;
  endDate: string;
  paymentStatus: string;
  milestoneStatus: string;
  lastUpdatedBy: string;
  lastUpdatedUserName: string;
  lastUpdatedDate: string | null;
}

export interface MBookMasterViewModel {
  id: string;
  workTemplateMilestoneId: string;
  paymentStatusId: string;
  length: number;
  width: number;
  heigth: number;
  actionableRoleId: string;
  divisionId: string;
  statusName: string;
  statusCode: string;
  paymentStatusName: string;
  paymentStatusCode: string;
  isActive: boolean;
  isActionable: boolean;
  isEditable: boolean;
  isSubmitted: boolean;
  workNotes: string;
  date: string;
  prefix: string;
  suffix: string;
  runningNumber: number;
  mBookNumber: string;
  milestoneName: string;
  workTemplateId: string;
  tenderNumber: string;
  districtName: string;
  divisionName: string;
  departmentId: string;
  gONumber: string;
  gODepartment: string;
  gOName: string;
  percentageCompleted: number;
  workType: string;
  subWorkType: string;
  files: FileMasterModel[] | null;
  approvalHistory: MBookApprovalHistoryViewModel[] | null;
  rejectedMbooks: MBookMasterViewModel[] | null;
  durationInDays: number;
  paymentPercentage: number;
  startDate: string;
  endDate: string;
  paymentStatus: string;
  milestoneStatus: string;
  strength: string;
  templateCode: string;
  mileStoneId: string;
  milestoneCode: string;
  milestoneAmount: number;
  actualAmount: number;
  isCompleted: boolean;
  lastUpdatedBy: string;
  lastUpdatedUserName: string;
  lastUpdatedDate: string | null;
}
export interface FileMasterModel {
  id: string;
  type: string;
  originalFileName: string;
  savedFileName: string;
  fileType: string;
  typeId: string;
  isActive: boolean;
  createdBy: string;
  createdByUserName: string;
  createdDate: string;
  modifiedBy: string;
  modifiedByUserName: string;
  modifiedDate: string;
  deletedBy: string;
  deletedByUserName: string;
  deletedDate: string;
  savedBy: string;
  savedByUserName: string;
  savedDate: string;
}
export interface MBookApprovalHistoryViewModel {

  id: string;
  mBookId: string;
  fromId: string;
  toId: string;
  statusEnum: string;
  documentName:string
  division:string;
  comments: string;
  fromRoleName: string;
  toRoleName: string;
  lastUpdatedBy: string;
  lastUpdatedUserName: string;
  lastUpdatedDate: string | null;
  type: string ;
  files: FileMasterModel[] | null;
  originalFileName: string;
  savedFileName: string ;
  fileType: string ;
  typeId: string ;
  typeName: string ;
  isActive: boolean ;
}
export interface MBookReportModel {
  id: string;
  workNotes: string;
  submittedDate: string;
  completedDate: string;
  date: string;
  actualAmount: number;
  mBookNumber: string;
  actionableRoleId: string;
  actionableRoleName: string;
  paymentStatusId: string;
  paymentStatusName: string;
  statusId: string;
  statusName: string;
  workId: string;
  workTemplateId: string;
  milestoneName: string;
  orderNumber: string;
  durationInDays: number;
  durationInDaysLeft: number;
  isPaymentRequired: boolean;
  paymentPercentage: number;
  milestoneStartDate: string;
  milestoneEndDate: string;
  milestoneCompletedDate: string;
  percentageCompleted: number;
  milestoneCode: string;
  isActive: boolean;
  milestoneAmount: number;
  milestoneActualAmount: number;
  milestoneIsCompleted: boolean;
  workTypeId: string;
  workType: string;
  subWorkTypeId: string;
  subWorkType: string;
  strength: string;
  workNumber: string;
  workTemplateName: string;
  division: string;
  district: string;
  districtName: string;
  divisionName: string;
  tenderNumber: string;
}
